# Generated by Django 3.1.7 on 2021-04-01 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Drone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dev_id', models.CharField(blank=True, max_length=500)),
                ('hardware_serial', models.CharField(blank=True, max_length=500)),
                ('payload_row', models.CharField(blank=True, max_length=5000)),
                ('meta_data', models.DateTimeField(blank=True)),
            ],
        ),
    ]
